#!/usr/bin/env python3
# /// script
# dependencies = [
#   "click>=8.1.7",
#   "rich>=13.0.0",
# ]
# requires-python = ">=3.13"
# ///
"""Hello world implementation."""

# pyright: reportMissingImports=false

import click
from rich.console import Console

console = Console()


@click.command()
@click.option("--name", default="World")
@click.option("--uppercase", is_flag=True)
def main(name: str, uppercase: bool) -> None:
    """Execute hello world greeting."""
    greeting = f"Hello, {name}!"

    if uppercase:
        greeting = greeting.upper()

    console.print(f"[bold green]{greeting}[/bold green]")
    console.print("[dim]This greeting was generated by a PEP 723 script[/dim]")


if __name__ == "__main__":
    main()
