name: Check Artifacts

on:
  push:
  pull_request:

jobs:
  check-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync
      - name: Check artifact metadata and sync status
        run: uv run --package dot-agent-kit dot-agent artifact check
